@baseURl = http://localhost:3333
@token = {{sign_in.response.body.token}}

# Sign up
POST {{baseURl}}/sign-up
Content-Type: application/json

{
  "username": "John Doe",
  "email": "john@example.com",
  "password": "password123",
  "confirmPassword": "password123"
}

###

# Sign in
# @name sign_in
POST {{baseURl}}/sign-in
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "password123",
  "confirmPassword": "password123"
}