@baseURl = http://localhost:3333
@token = {{sign_in.response.body.token}}
# Sign up
POST {{baseURl}}/sign-up
Content-Type: application/json

{
  "username": "John Doe",
  "email": "john@example.com",
  "password": "password123",
  "confirmPassword": "password123"
}

###

# Sign in
# @name sign_in
POST {{baseURl}}/sign-in
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "password123",
  "confirmPassword": "password123"
}

###

# Create task
# @name create_task
POST {{baseURl}}/tasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "My first task",
  "description": "This is the first task I am creating",
  "completed": false,
  "dueDate": "2024-07-10T00:00:00.000Z"
}

###

# Get tasks
# @name get_tasks
GET {{baseURl}}/tasks?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{token}}

###

# Get task
# @name get_task
GET {{baseURl}}/tasks/7275640c-6ee5-4a4b-b4dd-c40e0d4c276f
Authorization: Bearer {{token}}

###

# Update task
# @name update_task
PUT {{baseURl}}/tasks/7275640c-6ee5-4a4b-b4dd-c40e0d4c276f
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "My first task updated",
  "description": "This task was updated",
  "completed": true,
  "dueDate": "2024-07-10T00:00:00.000Z"
}